### ISSUE TITLE
Add module support

### ISSUE THREAD

**Issue by prologic** [prologic/monkey-lang#4]
Add module support to Monkey. Will will work something like this:

* A `MONKEYPATH` environment variable tells the Monkey interpreter/vm where to find modules.
* Monkey also looks for modules in the current working directory.

Importing a module looks like this:

```#!monkey
foo := import("foo")  // importing a single module
bar := import("foo/bar") // importing a namespace module
```

There is no scope *scope* in this issue for a package manager / ecosystem (*that will  come later*).

**Comment by mirimmad** [comment]
I was about to raise the same issue.
